// Maps to: tt-kmd/ioctl.h (ABI ground truth extraction)
//
// Compiles against the Linux tt-kmd public header with gcc on the Linux side
// and dumps sizeof/offsetof for every ABI struct plus the ioctl request codes.
// The output (docs/abi-ground-truth.txt) is the normative layout reference for
// the Windows header's static_asserts and the ioctl parity matrix.
//
// Build/run: tools/gen_abi_truth.sh

#include <stdio.h>
#include <stddef.h>
#include <sys/ioctl.h>
#include "../../tt-kmd/ioctl.h"

#define S(t) printf("sizeof %-45s %zu\n", #t, sizeof(struct t))
#define F(t, f) printf("offset %-45s %-28s %3zu %2zu\n", #t, #f, \
                       offsetof(struct t, f), sizeof(((struct t *)0)->f))

int main(void)
{
    printf("# ABI ground truth for tt-kmd ioctl.h, generated by abi_ground_truth.c\n");
    printf("# Baseline: ttkmd-2.10.0-rc1-1-g8c32c2b; x86_64; format:\n");
    printf("#   sizeof <struct> <bytes> | offset <struct> <field> <offset> <fieldsize>\n\n");

    printf("ioctl TENSTORRENT_IOCTL_GET_DEVICE_INFO   0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_GET_DEVICE_INFO);
    printf("ioctl TENSTORRENT_IOCTL_GET_HARVESTING    0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_GET_HARVESTING);
    printf("ioctl TENSTORRENT_IOCTL_QUERY_MAPPINGS    0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_QUERY_MAPPINGS);
    printf("ioctl TENSTORRENT_IOCTL_ALLOCATE_DMA_BUF  0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_ALLOCATE_DMA_BUF);
    printf("ioctl TENSTORRENT_IOCTL_FREE_DMA_BUF      0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_FREE_DMA_BUF);
    printf("ioctl TENSTORRENT_IOCTL_GET_DRIVER_INFO   0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_GET_DRIVER_INFO);
    printf("ioctl TENSTORRENT_IOCTL_RESET_DEVICE      0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_RESET_DEVICE);
    printf("ioctl TENSTORRENT_IOCTL_PIN_PAGES         0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_PIN_PAGES);
    printf("ioctl TENSTORRENT_IOCTL_LOCK_CTL          0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_LOCK_CTL);
    printf("ioctl TENSTORRENT_IOCTL_MAP_PEER_BAR      0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_MAP_PEER_BAR);
    printf("ioctl TENSTORRENT_IOCTL_UNPIN_PAGES       0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_UNPIN_PAGES);
    printf("ioctl TENSTORRENT_IOCTL_ALLOCATE_TLB      0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_ALLOCATE_TLB);
    printf("ioctl TENSTORRENT_IOCTL_FREE_TLB          0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_FREE_TLB);
    printf("ioctl TENSTORRENT_IOCTL_CONFIGURE_TLB     0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_CONFIGURE_TLB);
    printf("ioctl TENSTORRENT_IOCTL_SET_NOC_CLEANUP   0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_SET_NOC_CLEANUP);
    printf("ioctl TENSTORRENT_IOCTL_SET_POWER_STATE   0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_SET_POWER_STATE);
    printf("ioctl TENSTORRENT_IOCTL_EXPORT_TLB_DMABUF 0x%08lx\n", (unsigned long)TENSTORRENT_IOCTL_EXPORT_TLB_DMABUF);
    printf("\n");

    S(tenstorrent_get_device_info_in);
    F(tenstorrent_get_device_info_in, output_size_bytes);
    S(tenstorrent_get_device_info_out);
    F(tenstorrent_get_device_info_out, output_size_bytes);
    F(tenstorrent_get_device_info_out, vendor_id);
    F(tenstorrent_get_device_info_out, device_id);
    F(tenstorrent_get_device_info_out, subsystem_vendor_id);
    F(tenstorrent_get_device_info_out, subsystem_id);
    F(tenstorrent_get_device_info_out, bus_dev_fn);
    F(tenstorrent_get_device_info_out, max_dma_buf_size_log2);
    F(tenstorrent_get_device_info_out, pci_domain);
    F(tenstorrent_get_device_info_out, reserved);
    S(tenstorrent_get_device_info);

    S(tenstorrent_query_mappings_in);
    F(tenstorrent_query_mappings_in, output_mapping_count);
    F(tenstorrent_query_mappings_in, reserved);
    S(tenstorrent_mapping);
    F(tenstorrent_mapping, mapping_id);
    F(tenstorrent_mapping, reserved);
    F(tenstorrent_mapping, mapping_base);
    F(tenstorrent_mapping, mapping_size);
    S(tenstorrent_query_mappings);

    S(tenstorrent_allocate_dma_buf_in);
    F(tenstorrent_allocate_dma_buf_in, requested_size);
    F(tenstorrent_allocate_dma_buf_in, buf_index);
    F(tenstorrent_allocate_dma_buf_in, flags);
    F(tenstorrent_allocate_dma_buf_in, reserved0);
    F(tenstorrent_allocate_dma_buf_in, reserved1);
    S(tenstorrent_allocate_dma_buf_out);
    F(tenstorrent_allocate_dma_buf_out, physical_address);
    F(tenstorrent_allocate_dma_buf_out, mapping_offset);
    F(tenstorrent_allocate_dma_buf_out, size);
    F(tenstorrent_allocate_dma_buf_out, reserved0);
    F(tenstorrent_allocate_dma_buf_out, noc_address);
    F(tenstorrent_allocate_dma_buf_out, reserved1);
    S(tenstorrent_allocate_dma_buf);

    S(tenstorrent_free_dma_buf);

    S(tenstorrent_get_driver_info_in);
    F(tenstorrent_get_driver_info_in, output_size_bytes);
    S(tenstorrent_get_driver_info_out);
    F(tenstorrent_get_driver_info_out, output_size_bytes);
    F(tenstorrent_get_driver_info_out, driver_version);
    F(tenstorrent_get_driver_info_out, driver_version_major);
    F(tenstorrent_get_driver_info_out, driver_version_minor);
    F(tenstorrent_get_driver_info_out, driver_version_patch);
    F(tenstorrent_get_driver_info_out, reserved0);
    S(tenstorrent_get_driver_info);

    S(tenstorrent_reset_device_in);
    F(tenstorrent_reset_device_in, output_size_bytes);
    F(tenstorrent_reset_device_in, flags);
    S(tenstorrent_reset_device_out);
    F(tenstorrent_reset_device_out, output_size_bytes);
    F(tenstorrent_reset_device_out, result);
    S(tenstorrent_reset_device);

    S(tenstorrent_pin_pages_in);
    F(tenstorrent_pin_pages_in, output_size_bytes);
    F(tenstorrent_pin_pages_in, flags);
    F(tenstorrent_pin_pages_in, virtual_address);
    F(tenstorrent_pin_pages_in, size);
    S(tenstorrent_pin_pages_out);
    F(tenstorrent_pin_pages_out, physical_address);
    S(tenstorrent_pin_pages_out_extended);
    F(tenstorrent_pin_pages_out_extended, physical_address);
    F(tenstorrent_pin_pages_out_extended, noc_address);
    S(tenstorrent_pin_pages);

    S(tenstorrent_unpin_pages_in);
    F(tenstorrent_unpin_pages_in, virtual_address);
    F(tenstorrent_unpin_pages_in, size);
    F(tenstorrent_unpin_pages_in, reserved);
    S(tenstorrent_unpin_pages);

    S(tenstorrent_lock_ctl_in);
    F(tenstorrent_lock_ctl_in, output_size_bytes);
    F(tenstorrent_lock_ctl_in, flags);
    F(tenstorrent_lock_ctl_in, index);
    S(tenstorrent_lock_ctl_out);
    F(tenstorrent_lock_ctl_out, value);
    S(tenstorrent_lock_ctl);

    S(tenstorrent_map_peer_bar_in);
    F(tenstorrent_map_peer_bar_in, peer_fd);
    F(tenstorrent_map_peer_bar_in, peer_bar_index);
    F(tenstorrent_map_peer_bar_in, peer_bar_offset);
    F(tenstorrent_map_peer_bar_in, peer_bar_length);
    F(tenstorrent_map_peer_bar_in, flags);
    F(tenstorrent_map_peer_bar_in, reserved);
    S(tenstorrent_map_peer_bar_out);
    F(tenstorrent_map_peer_bar_out, dma_address);
    F(tenstorrent_map_peer_bar_out, reserved);
    S(tenstorrent_map_peer_bar);

    S(tenstorrent_allocate_tlb_in);
    F(tenstorrent_allocate_tlb_in, size);
    F(tenstorrent_allocate_tlb_in, reserved);
    S(tenstorrent_allocate_tlb_out);
    F(tenstorrent_allocate_tlb_out, id);
    F(tenstorrent_allocate_tlb_out, reserved0);
    F(tenstorrent_allocate_tlb_out, mmap_offset_uc);
    F(tenstorrent_allocate_tlb_out, mmap_offset_wc);
    F(tenstorrent_allocate_tlb_out, reserved1);
    S(tenstorrent_allocate_tlb);

    S(tenstorrent_free_tlb_in);
    F(tenstorrent_free_tlb_in, id);
    S(tenstorrent_free_tlb);

    S(tenstorrent_noc_tlb_config);
    F(tenstorrent_noc_tlb_config, addr);
    F(tenstorrent_noc_tlb_config, x_end);
    F(tenstorrent_noc_tlb_config, y_end);
    F(tenstorrent_noc_tlb_config, x_start);
    F(tenstorrent_noc_tlb_config, y_start);
    F(tenstorrent_noc_tlb_config, noc);
    F(tenstorrent_noc_tlb_config, mcast);
    F(tenstorrent_noc_tlb_config, ordering);
    F(tenstorrent_noc_tlb_config, linked);
    F(tenstorrent_noc_tlb_config, static_vc);
    F(tenstorrent_noc_tlb_config, reserved0);
    F(tenstorrent_noc_tlb_config, reserved1);
    S(tenstorrent_configure_tlb_in);
    F(tenstorrent_configure_tlb_in, id);
    F(tenstorrent_configure_tlb_in, reserved);
    F(tenstorrent_configure_tlb_in, config);
    S(tenstorrent_configure_tlb_out);
    F(tenstorrent_configure_tlb_out, reserved);
    S(tenstorrent_configure_tlb);

    S(tenstorrent_set_noc_cleanup);
    F(tenstorrent_set_noc_cleanup, argsz);
    F(tenstorrent_set_noc_cleanup, flags);
    F(tenstorrent_set_noc_cleanup, enabled);
    F(tenstorrent_set_noc_cleanup, x);
    F(tenstorrent_set_noc_cleanup, y);
    F(tenstorrent_set_noc_cleanup, noc);
    F(tenstorrent_set_noc_cleanup, reserved0);
    F(tenstorrent_set_noc_cleanup, addr);
    F(tenstorrent_set_noc_cleanup, data);

    S(tenstorrent_power_state);
    F(tenstorrent_power_state, argsz);
    F(tenstorrent_power_state, flags);
    F(tenstorrent_power_state, reserved0);
    F(tenstorrent_power_state, validity);
    F(tenstorrent_power_state, power_flags);
    F(tenstorrent_power_state, power_settings);

    S(tenstorrent_export_tlb_dmabuf);
    F(tenstorrent_export_tlb_dmabuf, argsz);
    F(tenstorrent_export_tlb_dmabuf, flags);
    F(tenstorrent_export_tlb_dmabuf, tlb_id);
    F(tenstorrent_export_tlb_dmabuf, fd);
    F(tenstorrent_export_tlb_dmabuf, offset);
    F(tenstorrent_export_tlb_dmabuf, size);

    return 0;
}
